USE [master]
GO
/****** Object:  Database [DBKOMGRIP]    Script Date: 6/16/2024 6:51:54 AM ******/
CREATE DATABASE [DBKOMGRIP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBKOMGRIP', FILENAME = N'D:\DBTest\DBKOMGRIP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBKOMGRIP_log', FILENAME = N'D:\DBTest\DBKOMGRIP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DBKOMGRIP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBKOMGRIP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBKOMGRIP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBKOMGRIP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBKOMGRIP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBKOMGRIP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBKOMGRIP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBKOMGRIP] SET  MULTI_USER 
GO
ALTER DATABASE [DBKOMGRIP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBKOMGRIP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBKOMGRIP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBKOMGRIP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBKOMGRIP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBKOMGRIP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DBKOMGRIP] SET QUERY_STORE = OFF
GO
USE [DBKOMGRIP]
GO
/****** Object:  User [TestUser]    Script Date: 6/16/2024 6:51:54 AM ******/
CREATE USER [TestUser] FOR LOGIN [TestUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [TestUser]
GO
/****** Object:  Table [dbo].[Tb_Login]    Script Date: 6/16/2024 6:51:54 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_Login](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](max) NULL,
	[password] [varchar](max) NULL,
	[name] [varchar](max) NULL,
	[position] [varchar](max) NULL,
 CONSTRAINT [PK_Tb_Login] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tb_TimeLog]    Script Date: 6/16/2024 6:51:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_TimeLog](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name_id] [int] NULL,
	[last_login] [datetime] NULL,
 CONSTRAINT [PK_Tb_TimeLog] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [DBKOMGRIP] SET  READ_WRITE 
GO
